# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da7b42e741f4b8f72a6fae8e7a08911e45e5480fe80a829d64924084cf25310d10ad7f9858330a562e193e8bf39654b6a793e61b3700daec34505e8cbca0167a

test:
  secret_key_base: 76452c5e7fd3c57aa40a36e2c78cebda60811e0f504ac42c193424c490eadd1b1ae114e054bce60400f68fbb749e9ce93d478db1616c5ba0922dca8a1b36e1e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
